fichas/fichas/urls.py
from django.contrib import admin
from django.urls import include, path
from fichasapp import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fichasapp.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path('usuarios/', views.usuarios, name='usuarios'),
    path('crear_usuario/', views.create_usuario, name='crear_usuario'), 
    path('modificar_usuario/<str:pk>', views.edit_usuario, name='modificar_usuario'),
    path('eliminar_usuario/<str:pk>', views.delete_usuario, name='eliminar_usuario'), 
    path('mostrar_usuario/<str:pk>', views.view_usuario, name='mostrar_usuario'), 
    path('fichas/', views.fichas, name='fichas'),
    path('crear_ficha/', views.create_ficha, name='crear_ficha'), 
    path('modificar_ficha/<str:pk>', views.edit_ficha, name='modificar_ficha'),
    path('eliminar_ficha/<str:pk>', views.delete_ficha, name='eliminar_ficha'), 
    path('mostrar_ficha/<str:pk>', views.view_ficha, name='mostrar_ficha'), 
]

fichas/fichasapp/urls.py
from django.urls import *
from . import views

app_name = 'fichasapp'

urlpatterns  = [
    path('', views.home, name='index'),
    path("accounts/", include("django.contrib.auth.urls")),
    path('usuarios/', views.usuarios, name='usuarios'),
    path('crear_usuario/', views.create_usuario, name='crear_usuario'), 
    path('modificar_usuario/<str:pk>', views.edit_usuario, name='modificar_usuario'),
    path('eliminar_usuario/<str:pk>', views.delete_usuario, name='eliminar_usuario'), 
    path('mostrar_usuario/<str:pk>', views.view_usuario, name='mostrar_usuario'), 
    path('fichas/', views.fichas, name='fichas'),
    path('crear_ficha/', views.create_ficha, name='crear_ficha'), 
    path('modificar_ficha/<str:pk>', views.edit_ficha, name='modificar_ficha'),
    path('eliminar_ficha/<str:pk>', views.delete_ficha, name='eliminar_ficha'), 
    path('mostrar_ficha/<str:pk>', views.view_ficha, name='mostrar_ficha'), 
]

fichas/fichasapp/models.py
from django.db import models
    
class Usuario(models.Model):
    ROL = (('Administrador', 'Administrador'),
    ('Funcionario', 'Funcionario'),
    ('Usuario', 'Usuario'),
    )
    nombre = models.CharField(max_length=50, null=True) 
    apellido = models.CharField(max_length=50, null=True)
    rut = models.CharField(max_length=13, null=True)
    correo = models.EmailField(max_length=50, null=True)
    rol = models.CharField(max_length=200, null=True, choices=ROL)

    def __str__(self):
        return self.nombre
    
class Ficha(models.Model):
    PREVISION = (('Fonasa', 'Fonasa'),
    ('Isapre', 'Isapre'),
    )
    SEXO = (('Masculino', 'Masculino'),
    ('Femenino', 'Femenino'),
    ('Intersexual', 'Intersexual'),
    )
    ISAPRE = (('Colmena', 'Colmena'),
    ('CruzBlanca', 'CruzBlanca'),
    ('Consalud', 'Consalud'),
    ('MasVda', 'MasVda'),
    ('BanMedica', 'BanMedica'),
    )
    rut = models.CharField(max_length=13)
    nombre = models.CharField(max_length=50) 
    apellido = models.CharField(max_length=50)
    fecha_nacimiento = models.DateTimeField()
    prevision_salud = models.CharField(max_length=200, null=True, choices=PREVISION)
    tipo_isapre = models.CharField(max_length=200, null=True, choices=ISAPRE)
    domicilio = models.CharField(max_length=100)
    sexo = models.CharField(max_length=200, null=True, choices=SEXO)

    def __str__(self):
        return self.nombre

fichas/fichasapp/forms.py
from django import forms
from django.forms import DateTimeInput
from .models import *


class UsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ('nombre', 'apellido', 'rut', 'correo', 'rol')
        labels = {
            'nombre': 'Nombre',
            'apellido': 'Apellido',
            'rut': 'RUT',
            'correo': 'Correo Electrónico',
            'rol': 'Rol',
        }
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'apellido': forms.TextInput(attrs={'class': 'form-control'}),
            'rut': forms.TextInput(attrs={'class': 'form-control'}),
            'correo': forms.EmailInput(attrs={'class': 'form-control'}),
            'rol': forms.Select(attrs={'class': 'form-select'}),
        }


class FichaForm(forms.ModelForm):

    class Meta:
        model = Ficha
        fields = ('rut', 'nombre', 'apellido', 'fecha_nacimiento', 'prevision_salud', 'tipo_isapre', 'domicilio', 'sexo')
        labels = {
            'rut': 'RUT',
            'nombre': 'Nombre',
            'apellido': 'Apellido',
            'fecha_nacimiento': 'Fecha de Nacimiento',
            'prevision_salud': 'Previsión de Salud',
            'tipo_isapre':'Tipo_isapre',
            'domicilio': 'Domicilio',
            'sexo': 'Sexo',
        }
        widgets = {
            'rut': forms.TextInput(attrs={'class': 'form-control'}),
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'apellido': forms.TextInput(attrs={'class': 'form-control'}),
            'fecha_nacimiento': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'prevision_salud': forms.Select(attrs={'class': 'form-select'}),
            'tipo_isapre': forms.Select(attrs={'class': 'form-select'}),
            'domicilio': forms.TextInput(attrs={'class': 'form-control'}),
            'sexo': forms.Select(attrs={'class': 'form-select'}),
        }

fichas/fichasapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from fichasapp.forms import *
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required

def home(request):
    return render(request, 'index.html')


def usuarios(request):
    usuarios = Usuario.objects.all()
    return render(request, 'usuarios/usuarios.html', {'usuarios': usuarios})


def create_usuario(request):
    form = UsuarioForm()
    if request.method == 'POST':
        form = UsuarioForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/usuarios')

    context = {'form': form}
    return render(request, 'usuarios/user_form.html', context)


def edit_usuario(request, pk):
    usuario = Usuario.objects.get(id=pk)
    form = UsuarioForm(instance=usuario)
    if request.method == 'POST':
        form = UsuarioForm(request.POST, instance=usuario)
        if form.is_valid():
            form.save()
            return redirect('/usuarios')
    context = {'form': form}
    return render(request, 'usuarios/user_form.html', context)


def delete_usuario(request, pk):
    usuario = Usuario.objects.get(id=pk)
    if request.method == "POST":
        usuario.delete()
        return redirect('/usuarios')
    context = {'usuario': usuario}
    return render(request, 'usuarios/delete_usuario.html', context)


def view_usuario(request, pk):
    usuario = Usuario.objects.get(id=pk)
    context = {'usuario': usuario}
    return render(request, 'usuarios/view_usuario.html', context)


def fichas(request):
    fichas = Ficha.objects.all()
    context = {
        'fichas': fichas,
    }
    return render(request, 'fichas/fichas.html', context)


def create_ficha(request):
    if request.method == 'POST':
        form = FichaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('fichas')
    else:
        form = FichaForm()
    
    context = {
        'form': form,
    }
    return render(request, 'fichas/ficha_form.html', context)


def delete_ficha(request, pk):
    ficha = get_object_or_404(Ficha, id=pk)
    if request.method == 'POST':
        ficha.delete()
        return redirect('fichas')
    
    context = {
        'ficha': ficha,
    }
    return render(request, 'fichas/delete_ficha.html', context)


def view_ficha(request, pk):
    ficha = Ficha.objects.get(id=pk)
    context = {'ficha': ficha}
    return render(request, 'fichas/view_ficha.html', context)


def edit_ficha(request, pk):
    ficha = Ficha.objects.get(id=pk)
    form = FichaForm(instance=ficha)
    if request.method == 'POST':
        form = FichaForm(request.POST, instance=ficha)
        if form.is_valid():
            form.save()
            return redirect('/fichas')
    context = {'form': form}
    return render(request, 'fichas/ficha_form.html', context)

def login(request):
    return render(request, '/login.html')

fichas/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}Fichas Medicas{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  
  {% load bootstrap5 %}
  {% bootstrap_css %}

</head>
<body>
  <div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                <a href="/"
                    class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                    <h4 class="d-flex align-items-center">
                      <img src="{% static 'images/logo.png' %}" alt="404" class="me-2" style="max-height: 80px;">
                      <span class="fs-5 d-none d-sm-inline">Fichas Médicas</span>
                    </h4>
                </a>
                <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start"
                    id="menu">
                    <li class="nav-item">
                        <a href="{% url 'usuarios' %}" class="nav-link align-middle px-0">
                            <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Usuarios</span>
                        </a>
                    </li>
                    <li class="nav-item">
                      <a href="{% url 'fichas' %}" class="nav-link align-middle px-0">
                          <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Fichas</span>
                      </a>
                  </li>
                </ul>
                <hr>
                <div class="dropdown pb-4">
                    {% if user.is_authenticated %}
                    <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle"
                        id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="https://github.com/mdo.png" alt="hugenerd" width="30" height="30"
                            class="rounded-circle">
                        <span class="d-none d-sm-inline mx-1">{{user.get_full_name}}</span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
                        <li><a class="dropdown-item" href="{% url 'logout' %}">Cerrar sesión</a></li>
                    </ul>
                    {% else %}
                    <a href="{% url 'login' %}" class="d-flex align-items-center text-white text-decoration-none"
                        id="dropdownUser1">Iniciar sesión</a>
                    {%endif%}
                </div>
            </div>
        </div>
        <div class="col py-3">
            <div class="row">
                {% if user.is_authenticated %}
                <div class="col-md-12">
                  <div class="col-md-12 p-2">
                    {% block content %}
                    {% endblock content %}
                  </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
      <!-- Main Content -->

  {% bootstrap_javascript %}

</body>
</html>

fichas/templates/fichas/delete_ficha.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h1>Eliminar Ficha</h1>
  <p>¿Está seguro que desea eliminar la ficha?</p>
  <p><strong>RUT:</strong> {{ ficha.rut }}</p>
  <p><strong>Nombre:</strong> {{ ficha.nombre }}</p>
  <p><strong>Apellido:</strong> {{ ficha.apellido }}</p>
  <p><strong>Fecha de Nacimiento:</strong> {{ ficha.fecha_nacimiento|date:'d/m/Y' }}</p>
  <p><strong>Previsión de Salud:</strong> {{ ficha.prevision_salud }}</p>
  <p><strong>Domicilio:</strong> {{ ficha.domicilio }}</p>
  <p><strong>Sexo:</strong> {{ ficha.sexo }}</p>
  <form method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Eliminar</button>
    <a href="{% url 'fichas' %}" class="btn btn-secondary">Cancelar</a>
  </form>
</div>
{% endblock %}

fichas/templates/fichas/ficha_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h1>Creación/Edición de Fichas Médicas</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="btn-group mt-2">
      <input type="submit" class="btn btn-primary" name="Submit" value="Guardar">
      <a href="{% url 'fichas' %}" class="btn btn-secondary">Regresar</a>
  </div>
  </form>
</div>
{% endblock %}

fichas/templates/fichas/fichas.html
{% extends 'base.html' %}

{% block content %}
<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row container d-flex justify-content-center">
        <div class="col-lg-12 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">Fichas Médicas</h4>
                  <p class="card-description">
                    Lista de Pacientes
                  </p>
                  <div class="table-responsive">
                    <a name="" id="" class="btn btn-primary" href="{% url 'crear_ficha' %}" role="button">Crear Ficha</a>
                    <table class="table">
                      <thead>
                        <tr>
                          <th>Nombre</th>
                          <th>Apellido</th>
                          <th>Rut</th>
                          <th>Prevision</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for ficha in fichas %}
                        <tr>
                          <td>{{ ficha.nombre }}</td>
                          <td>{{ ficha.apellido }}</td>
                          <td>{{ ficha.rut }}</td>
                          <td>{{ ficha.prevision_salud }}</td>
                          <td class="btn-group" role="group" aria-label="Basic mixed styles example">
                            <a name="" id="" class="btn btn-primary" href="{% url 'modificar_ficha' ficha.id %}" role="button">Modificar</a>
                            <a name="" id="" class="btn btn-secondary" href="{% url 'mostrar_ficha' ficha.id %}" role="button">Ver</a>
                            <a name="" id="" class="btn btn-danger" href="{% url 'eliminar_ficha' ficha.id %}" role="button">Eliminar</a>
                          </td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
            </div>
              </div>
            </div>
{% endblock content %}

fichas/templates/fichas/view_ficha.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="card">
    <div class="card-body">
      <div class="container">
        <div class="container">
            <h1 class="mt-5">Detalles del Paciente</h1>
            <ul class="list-group mt-4">
                <li class="list-group-item"><strong>Nombre:</strong> {{ ficha.nombre }}</li>
                <li class="list-group-item"><strong>Apellido:</strong> {{ ficha.apellido }}</li>
                <li class="list-group-item"><strong>RUT:</strong> {{ ficha.rut }}</li>
                <li class="list-group-item"><strong>Fecha Nacimiento:</strong> {{ ficha.fecha_nacimiento|date:'d/m/Y' }}</li>
                <li class="list-group-item"><strong>Prevision Salud:</strong> {{ ficha.prevision_salud }}</li>
                {%if ficha.prevision_salud == 'Isapre' %}
                <li class="list-group-item"><strong>Tipo de Isapre:</strong> {{ ficha.tipo_isapre }}</li>
                {% endif %}
                <li class="list-group-item"><strong>Domicilio:</strong> {{ ficha.domicilio }}</li>
                <li class="list-group-item"><strong>Sexo:</strong> {{ ficha.sexo }}</li>
            </ul>
            <a href="{% url 'fichas' %}" class="btn btn-primary mt-4">Regresar</a>
        </div>
    </div>
    </div>
</div>
{% endblock %}

fichas/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% endblock %}


fichas/templates/usuarios/delete_usuario.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="card">
    <div class="card-body">
      <div class="container">
        <h1 class="mt-5">Eliminar a {{usuario.nombre}} {{usuario.apellido}}</h1>
        <form action="{% url 'eliminar_usuario' usuario.id %}" method="POST">
            {% csrf_token %}
            <div class="alert alert-danger mt-4">
                ¿Estás seguro de que deseas eliminar este usuario?
            </div>
            <a href="{% url 'usuarios' %}" class="btn btn-secondary mt-4">Cancelar</a>
            <input type="submit" class="btn btn-danger mt-4" name="confirm" value="Confirmar">
        </form>
    </div>
    </div>
</div>

{% endblock %}

fichas/templates/usuarios/user_form.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="card">
    <div class="card-body">
        <div class="container">
            <form action="" method="POST">
                <h1 class="mt-5">Creación/Edición de Usuario</h1>
                {% csrf_token %}
                <div class="form-group mt-4">
                    {{ form }}
                </div>
                <div class="btn-group mt-2">
                    <input type="submit" class="btn btn-primary" name="Submit" value="Guardar">
                    <a href="{% url 'usuarios' %}" class="btn btn-secondary">Regresar</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

fichas/templates/usuarios/usuarios.html
{% extends 'base.html' %}

{% block content %}
<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row container d-flex justify-content-center">
        <div class="col-lg-12 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <h4 class="card-title">Usuarios</h4>
                  <p class="card-description">
                    Lista de Usuarios
                  </p>
                  <div class="table-responsive">
                    <a name="" id="" class="btn btn-primary" href="{% url 'crear_usuario' %}" role="button">Crear Usuario</a>
                    <table class="table">
                      <thead>
                        <tr>
                          <th>Nombre</th>
                          <th>Apellido</th>
                          <th>Rut</th>
                          <th>Rol</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for usuario in usuarios %}
                        <tr>
                          <td>{{usuario.nombre}}</td>
                          <td>{{usuario.apellido}}</td>
                          <td>{{usuario.rut}}</td>
                          <td>{{usuario.rol}}</td>
                          <td class="btn-group" role="group" aria-label="Basic mixed styles example">
                            <a name="" id="" class="btn btn-primary" href="{% url 'modificar_usuario' usuario.id %}" role="button">Modificar</a>
                            <a name="" id="" class="btn btn-secondary" href="{% url 'mostrar_usuario' usuario.id %}" role="button">Ver</a>
                            <a name="" id="" class="btn btn-danger" href="{% url 'eliminar_usuario' usuario.id %}" role="button">Eliminar</a>
                          </td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
            </div>
              </div>
            </div>
{% endblock content %}

fichas/templates/usuarios/view_usuario.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="card">
    <div class="card-body">
      <div class="container">
        <div class="container">
            <h1 class="mt-5">Detalles del Usuario</h1>
            <ul class="list-group mt-4">
                <li class="list-group-item"><strong>Nombre:</strong> {{ usuario.nombre }}</li>
                <li class="list-group-item"><strong>Apellido:</strong> {{ usuario.apellido }}</li>
                <li class="list-group-item"><strong>RUT:</strong> {{ usuario.rut }}</li>
                <li class="list-group-item"><strong>Correo:</strong> {{ usuario.correo }}</li>
                <li class="list-group-item"><strong>Rol:</strong> {{ usuario.get_rol_display }}</li>
            </ul>
            <a href="{% url 'usuarios' %}" class="btn btn-primary mt-4">Regresar</a>
        </div>
    </div>
    </div>
</div>
{% endblock %}
